# generated by datamodel-codegen:
#   filename:  https://api.iri.nersc.gov/openapi.json
#   timestamp: 2026-08-30T18:15:36+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, conint, constr


class AllocationUnit(str, Enum):
    node_hours = "node_hours"
    bytes = "bytes"
    inodes = "inodes"


class BodyUpload(BaseModel):
    file: bytes = Field(
        ..., description="File to be uploaded as `multipart/form-data`", title="File"
    )


class Capability(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(
        ...,
        description="The unique identifier for the object. Typically a UUID or URN.",
        examples=["urn:iri:object:1234"],
        title="Id",
    )
    name: str | None = Field(
        None,
        description="The long name of the object.",
        examples=["Perlmutter GPU"],
        title="Name",
    )
    description: str | None = Field(
        None,
        description="Human-readable description of the object.",
        examples=["High-performance GPU compute resource"],
        title="Description",
    )
    last_modified: AwareDatetime | None = Field(
        None,
        description="ISO 8601 timestamp when this object was last modified.",
        examples=["2026-02-21T12:00:00Z"],
        title="Last Modified",
    )
    units: list[AllocationUnit] = Field(
        ...,
        description="Allocation units supported by this capability",
        examples=[["node_hours"]],
        title="Units",
    )
    self_uri: str = Field(
        ..., description="The canonical URL of this object", title="Self Uri"
    )


class CompressionType(str, Enum):
    none = "none"
    bzip2 = "bzip2"
    gzip = "gzip"
    xz = "xz"


class Endpoint(str, Enum):
    compute = "compute"
    filesystem = "filesystem"


class Facility(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(
        ...,
        description="The unique identifier for the object. Typically a UUID or URN.",
        examples=["urn:iri:object:1234"],
        title="Id",
    )
    name: str | None = Field(
        None,
        description="The long name of the object.",
        examples=["Perlmutter GPU"],
        title="Name",
    )
    description: str | None = Field(
        None,
        description="Human-readable description of the object.",
        examples=["High-performance GPU compute resource"],
        title="Description",
    )
    last_modified: AwareDatetime = Field(
        ...,
        description="ISO 8601 timestamp when this object was last modified.",
        examples=["2026-02-21T12:00:00Z"],
        title="Last Modified",
    )
    short_name: str | None = Field(
        None,
        description="Common or short name of the Facility.",
        examples=["ESnet"],
        title="Short Name",
    )
    organization_name: str | None = Field(
        None,
        description="Operating organization's name.",
        examples=["Energy Sciences Network"],
        title="Organization Name",
    )
    support_uri: AnyUrl | None = Field(
        None,
        description="Link to facility support portal.",
        examples=["https://support.es.net"],
        title="Support Uri",
    )
    self_uri: str = Field(
        ..., description="The canonical URL of this object", title="Self Uri"
    )
    site_uris: list[str] = Field(
        ..., description="URIs of associated Sites.", title="Site Uris"
    )


class IncidentType(str, Enum):
    planned = "planned"
    unplanned = "unplanned"
    reservation = "reservation"


class JobAttributes(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    duration: conint(ge=1) | None = Field(
        None,
        description="Duration in seconds",
        examples=[30, 60, 120],
        title="Duration",
    )
    queue_name: constr(min_length=1) | None = Field(
        None,
        description="Name of the queue or partition to submit the job to",
        examples=["debug"],
        title="Queue Name",
    )
    account: constr(min_length=1) | None = Field(
        None,
        description="Account or project to charge for resource usage",
        examples=["proj123"],
        title="Account",
    )
    reservation_id: constr(min_length=1) | None = Field(
        None,
        description="ID of a reservation to use for the job",
        examples=["resv-42"],
        title="Reservation Id",
    )
    custom_attributes: dict[str, str] | None = Field(
        None,
        description="Custom scheduler-specific attributes as key-value pairs",
        examples=[{"constraint": "gpu"}],
        title="Custom Attributes",
    )


class JobState(str, Enum):
    new = "new"
    queued = "queued"
    held = "held"
    active = "active"
    completed = "completed"
    failed = "failed"
    canceled = "canceled"


class JobStatus(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    state: JobState = Field(
        ..., description="Current state of the job", examples=["queued"]
    )
    time: float | None = Field(
        None,
        description="Timestamp associated with the status (seconds since epoch)",
        examples=[1708531200.0],
        title="Time",
    )
    message: str | None = Field(
        None,
        description="Human-readable status message",
        examples=["Job is waiting in queue"],
        title="Message",
    )
    exit_code: int | None = Field(
        None,
        description="Process exit code if the job has finished",
        examples=[0],
        title="Exit Code",
    )
    meta_data: dict[str, Any] | None = Field(
        None,
        description="Backend-specific metadata associated with the job status",
        title="Meta Data",
    )


class PostCompressRequest(BaseModel):
    path: str | None = Field(
        None,
        description="Source file or directory path",
        examples=["/home/user/dir"],
        title="Path",
    )
    target_path: str = Field(
        ...,
        description="Path to the compressed file",
        examples=["/home/user/file.tar.gz"],
        title="Target Path",
    )
    match_pattern: str | None = Field(
        None,
        description="Regex pattern to filter files to compress",
        examples=[".*\\.txt$"],
        title="Match Pattern",
    )
    dereference: bool | None = Field(
        False,
        description="If set to `true`, it follows symbolic links and archive the files they point to instead of the links themselves.",
        examples=[True],
        title="Dereference",
    )
    compression: CompressionType | None = Field(
        "gzip",
        description="Defines the type of compression to be used. By default gzip is used.",
        examples=["gzip"],
    )


class PostCopyRequest(BaseModel):
    path: str | None = Field(
        None,
        description="Source file or directory path",
        examples=["/home/user/dir"],
        title="Path",
    )
    target_path: str = Field(
        ...,
        description="Target path of the copy operation",
        examples=["/home/user/dir/file.new"],
        title="Target Path",
    )
    dereference: bool | None = Field(
        False,
        description="If set to `true`, it follows symbolic links and copies the files they point to instead of the links themselves.",
        examples=[True],
        title="Dereference",
    )


class PostExtractRequest(BaseModel):
    path: str | None = Field(
        None,
        description="Source file or directory path",
        examples=["/home/user/dir"],
        title="Path",
    )
    target_path: str = Field(
        ...,
        description="Path to the directory where to extract the compressed file",
        examples=["/home/user/dir"],
        title="Target Path",
    )
    compression: CompressionType | None = Field(
        "gzip",
        description="Defines the type of compression to be used. By default gzip is used.",
        examples=["gzip"],
    )


class PostFileSymlinkRequest(BaseModel):
    path: str | None = Field(
        None,
        description="Source file or directory path",
        examples=["/home/user/dir"],
        title="Path",
    )
    link_path: str = Field(
        ...,
        description="Path to the new symlink",
        examples=["/home/user/newlink"],
        title="Link Path",
    )


class PostMakeDirRequest(BaseModel):
    path: str | None = Field(
        None,
        description="Source file or directory path",
        examples=["/home/user/dir"],
        title="Path",
    )
    parent: bool | None = Field(
        False,
        description="If set to `true` creates all its parent directories if they do not already exist",
        examples=[True],
        title="Parent",
    )


class PostMoveRequest(BaseModel):
    path: str | None = Field(
        None,
        description="Source file or directory path",
        examples=["/home/user/dir"],
        title="Path",
    )
    target_path: str = Field(
        ...,
        description="Target path of the move operation",
        examples=["/home/user/dir/file.new"],
        title="Target Path",
    )


class Problem(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: AnyUrl = Field(
        ...,
        description="A URI reference that identifies the problem type.",
        title="Type",
    )
    status: conint(ge=100, le=599) = Field(
        ...,
        description="The HTTP status code for this occurrence.",
        examples=[404],
        title="Status",
    )
    title: str | None = Field(
        None,
        description="Short human-readable summary.",
        examples=["Not Found"],
        title="Title",
    )
    detail: str | None = Field(
        None,
        description="Human-readable explanation.",
        examples=["Descriptive text."],
        title="Detail",
    )
    instance: str = Field(
        ...,
        description="A URI reference identifying this occurrence.",
        examples=["http://localhost/api/v1/resource/123"],
        title="Instance",
    )


class Project(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(
        ...,
        description="Unique identifier of the project.",
        examples=["proj-abc123"],
        title="Id",
    )
    name: str = Field(
        ...,
        description="Human-readable name of the project.",
        examples=["Climate Simulation"],
        title="Name",
    )
    description: str = Field(
        ...,
        description="Detailed description of the project.",
        examples=["Research project studying atmospheric dynamics."],
        title="Description",
    )
    user_ids: list[str] = Field(
        ...,
        description="List of user identifiers participating in the project.",
        examples=[["user-123", "user-456"]],
        title="User Ids",
    )
    last_modified: AwareDatetime = Field(
        ...,
        description="Timestamp of the last modification of the project.",
        examples=["2026-02-21T14:30:00Z"],
        title="Last Modified",
    )
    self_uri: str = Field(
        ..., description="URI to this project resource", title="Self Uri"
    )


class PutFileChmodRequest(BaseModel):
    path: str | None = Field(
        None,
        description="Source file or directory path",
        examples=["/home/user/dir"],
        title="Path",
    )
    mode: str = Field(
        ...,
        description="Mode in octal permission format",
        examples=["777"],
        title="Mode",
    )


class PutFileChownRequest(BaseModel):
    path: str | None = Field(
        None,
        description="Source file or directory path",
        examples=["/home/user/dir"],
        title="Path",
    )
    owner: str | None = Field(
        "",
        description="User name of the new user owner of the file",
        examples=["user"],
        title="Owner",
    )
    group: str | None = Field(
        "",
        description="Group name of the new group owner of the file",
        examples=["my-group"],
        title="Group",
    )


class Resolution(str, Enum):
    unresolved = "unresolved"
    cancelled = "cancelled"
    completed = "completed"
    extended = "extended"
    pending = "pending"


class ResourceSpec(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    node_count: conint(ge=1) | None = Field(
        None,
        description="Number of compute nodes to allocate",
        examples=[2],
        title="Node Count",
    )
    process_count: conint(ge=1) | None = Field(
        None,
        description="Total number of processes to launch",
        examples=[64],
        title="Process Count",
    )
    processes_per_node: conint(ge=1) | None = Field(
        None,
        description="Number of processes to launch per node",
        examples=[32],
        title="Processes Per Node",
    )
    cpu_cores_per_process: conint(ge=1) | None = Field(
        None,
        description="Number of CPU cores to allocate per process",
        examples=[2],
        title="Cpu Cores Per Process",
    )
    gpu_cores_per_process: conint(ge=1) | None = Field(
        None,
        description="Number of GPU cores to allocate per process",
        examples=[1],
        title="Gpu Cores Per Process",
    )
    exclusive_node_use: bool | None = Field(
        True,
        description="Whether to request exclusive use of allocated nodes",
        examples=[True],
        title="Exclusive Node Use",
    )
    memory: conint(ge=1) | None = Field(
        None,
        description="Amount of memory to allocate in bytes",
        examples=[17179869184],
        title="Memory",
    )


class ResourceType(str, Enum):
    website = "website"
    service = "service"
    compute = "compute"
    system = "system"
    storage = "storage"
    network = "network"
    unknown = "unknown"


class Site(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(
        ...,
        description="The unique identifier for the object. Typically a UUID or URN.",
        examples=["urn:iri:object:1234"],
        title="Id",
    )
    name: str | None = Field(
        None,
        description="The long name of the object.",
        examples=["Perlmutter GPU"],
        title="Name",
    )
    description: str | None = Field(
        None,
        description="Human-readable description of the object.",
        examples=["High-performance GPU compute resource"],
        title="Description",
    )
    last_modified: AwareDatetime = Field(
        ...,
        description="ISO 8601 timestamp when this object was last modified.",
        examples=["2026-02-21T12:00:00Z"],
        title="Last Modified",
    )
    short_name: str | None = Field(
        None,
        description="Common or short name of the Site.",
        examples=["NERSC"],
        title="Short Name",
    )
    operating_organization: str | None = Field(
        ...,
        description="Organization operating the Site.",
        examples=["Lawrence Berkeley National Laboratory"],
        title="Operating Organization",
    )
    country_name: str | None = Field(
        None,
        description="Country name of the Location.",
        examples=["United States"],
        title="Country Name",
    )
    locality_name: str | None = Field(
        None,
        description="City or locality name of the Location.",
        examples=["Berkeley"],
        title="Locality Name",
    )
    state_or_province_name: str | None = Field(
        None,
        description="State or province name of the Location.",
        examples=["California"],
        title="State Or Province Name",
    )
    street_address: str | None = Field(
        None,
        description="Street address of the Location.",
        examples=["1 Cyclotron Rd"],
        title="Street Address",
    )
    unlocode: str | None = Field(
        None,
        description="United Nations trade and transport location code.",
        examples=["USOAK"],
        title="Unlocode",
    )
    altitude: float | None = Field(
        None, description="Altitude of the Location.", examples=[52.0], title="Altitude"
    )
    latitude: float | None = Field(
        None,
        description="Latitude of the Location.",
        examples=[37.8762],
        title="Latitude",
    )
    longitude: float | None = Field(
        None,
        description="Longitude of the Location.",
        examples=[-122.2506],
        title="Longitude",
    )
    self_uri: str = Field(
        ..., description="The canonical URL of this object", title="Self Uri"
    )
    resource_uris: list[str] = Field(
        ..., description="URIs of Resources hosted at this Site.", title="Resource Uris"
    )


class Status(str, Enum):
    up = "up"
    down = "down"
    degraded = "degraded"
    unknown = "unknown"


class TaskCommand(BaseModel):
    router: str = Field(
        ...,
        description="Router name the task comes from",
        examples=["filesystem"],
        title="Router",
    )
    command: str = Field(
        ..., description="Command to execute", examples=["chmod"], title="Command"
    )
    args: dict[str, Any] = Field(
        ...,
        description="Command arguments as key-value pairs",
        examples=[{"mode": "755", "path": "/home/user/file"}],
        title="Args",
    )


class TaskStatus(str, Enum):
    pending = "pending"
    active = "active"
    completed = "completed"
    failed = "failed"
    canceled = "canceled"


class TaskSubmitResponse(BaseModel):
    task_id: str = Field(
        ...,
        description="Identifier of the submitted task",
        examples=["task-123"],
        title="Task Id",
    )
    task_uri: str = Field(
        ..., description="The list of past events in this incident", title="Task Uri"
    )


class VolumeMount(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    source: constr(min_length=1) = Field(
        ...,
        description="The source path on the host system to mount",
        examples=["/data/project"],
        title="Source",
    )
    target: constr(min_length=1) = Field(
        ...,
        description="The target path inside the container where the volume will be mounted",
        examples=["/mnt/data"],
        title="Target",
    )
    read_only: bool | None = Field(
        True,
        description="Whether the mount should be read-only",
        examples=[True],
        title="Read Only",
    )


class AllocationEntry(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    allocation: float = Field(
        ...,
        description="Total allocation amount granted.",
        examples=[100000.0],
        title="Allocation",
    )
    usage: float = Field(
        ...,
        description="Amount of allocation consumed.",
        examples=[52342.5],
        title="Usage",
    )
    unit: AllocationUnit = Field(
        ...,
        description="Unit of the allocation (e.g., node_hours, bytes).",
        examples=["node_hours"],
    )


class Container(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    image: constr(min_length=1) = Field(
        ...,
        description="The container image to use (e.g., 'docker.io/library/ubuntu:latest')",
        examples=["docker.io/library/ubuntu:latest"],
        title="Image",
    )
    volume_mounts: list[VolumeMount] | None = Field(
        None,
        description="List of volume mounts for the container",
        title="Volume Mounts",
    )


class Event(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(
        ...,
        description="The unique identifier for the object. Typically a UUID or URN.",
        examples=["urn:iri:object:1234"],
        title="Id",
    )
    name: str | None = Field(
        None,
        description="The long name of the object.",
        examples=["Perlmutter GPU"],
        title="Name",
    )
    description: str | None = Field(
        None,
        description="Human-readable description of the object.",
        examples=["High-performance GPU compute resource"],
        title="Description",
    )
    last_modified: AwareDatetime = Field(
        ...,
        description="ISO 8601 timestamp when this object was last modified.",
        examples=["2026-02-21T12:00:00Z"],
        title="Last Modified",
    )
    occurred_at: AwareDatetime = Field(
        ...,
        description="Timestamp when the event occurred",
        examples=["2026-02-21T12:00:00Z"],
        title="Occurred At",
    )
    status: Status = Field(
        ...,
        description="Status of the resource at the time of the event",
        examples=["down"],
    )
    self_uri: str = Field(
        ..., description="The canonical URL of this object", title="Self Uri"
    )
    resource_uri: str = Field(
        ..., description="The resource belonging to this event", title="Resource Uri"
    )
    incident_uri: str | None = Field(
        ..., description="The event's incident", title="Incident Uri"
    )


class Incident(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(
        ...,
        description="The unique identifier for the object. Typically a UUID or URN.",
        examples=["urn:iri:object:1234"],
        title="Id",
    )
    name: str | None = Field(
        None,
        description="The long name of the object.",
        examples=["Perlmutter GPU"],
        title="Name",
    )
    description: str | None = Field(
        None,
        description="Human-readable description of the object.",
        examples=["High-performance GPU compute resource"],
        title="Description",
    )
    last_modified: AwareDatetime = Field(
        ...,
        description="ISO 8601 timestamp when this object was last modified.",
        examples=["2026-02-21T12:00:00Z"],
        title="Last Modified",
    )
    status: Status = Field(
        ..., description="Current status of the incident", examples=["degraded"]
    )
    start: AwareDatetime = Field(
        ...,
        description="Incident start time",
        examples=["2026-02-21T12:00:00Z"],
        title="Start",
    )
    end: AwareDatetime | None = Field(
        None,
        description="Incident end time",
        examples=["2026-02-21T14:00:00Z"],
        title="End",
    )
    type: IncidentType = Field(
        ..., description="Type of incident", examples=["planned"]
    )
    resolution: Resolution = Field(
        ..., description="Resolution status of the incident", examples=["pending"]
    )
    self_uri: str = Field(
        ..., description="The canonical URL of this object", title="Self Uri"
    )
    event_uris: list[str] = Field(
        ..., description="The list of past events in this incident", title="Event Uris"
    )
    resource_uris: list[str] = Field(
        ...,
        description="The list of resources that may be impacted by this incident",
        title="Resource Uris",
    )


class JobSpec(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    executable: constr(min_length=1) | None = Field(
        None,
        description="Path to the executable to run. If container is specified, this will be used as the entrypoint to the container.",
        examples=["/usr/bin/python"],
        title="Executable",
    )
    container: Container | None = Field(
        None, description="Container specification for containerized execution"
    )
    arguments: list[str] | None = Field(
        None,
        description="Command-line arguments to pass to the executable or container",
        examples=[["-n", "100"]],
        title="Arguments",
    )
    directory: constr(min_length=1) | None = Field(
        None,
        description="Working directory for the job",
        examples=["/home/user/work"],
        title="Directory",
    )
    name: constr(min_length=1) | None = Field(
        None, description="Name of the job", examples=["my-job"], title="Name"
    )
    inherit_environment: bool | None = Field(
        True,
        description="Whether to inherit the environment variables from the submission environment",
        examples=[True],
        title="Inherit Environment",
    )
    environment: dict[str, str] | None = Field(
        None,
        description="Environment variables to set for the job. If container is specified, these will be set inside the container.",
        examples=[{"OMP_NUM_THREADS": "4"}],
        title="Environment",
    )
    stdin_path: constr(min_length=1) | None = Field(
        None,
        description="Path to file to use as standard input",
        examples=["/home/user/input.txt"],
        title="Stdin Path",
    )
    stdout_path: constr(min_length=1) | None = Field(
        None,
        description="Path to file to write standard output",
        examples=["/home/user/output.txt"],
        title="Stdout Path",
    )
    stderr_path: constr(min_length=1) | None = Field(
        None,
        description="Path to file to write standard error",
        examples=["/home/user/error.txt"],
        title="Stderr Path",
    )
    resources: ResourceSpec | None = Field(
        None, description="Resource requirements for the job"
    )
    attributes: JobAttributes | None = Field(
        None,
        description="Additional job attributes such as duration, queue, and account",
    )
    pre_launch: constr(min_length=1) | None = Field(
        None,
        description="Script or commands to run before launching the job",
        examples=["module load cuda"],
        title="Pre Launch",
    )
    post_launch: constr(min_length=1) | None = Field(
        None,
        description="Script or commands to run after the job completes",
        examples=["echo done"],
        title="Post Launch",
    )
    launcher: constr(min_length=1) | None = Field(
        None,
        description="Job launcher to use (e.g., 'mpirun', 'srun')",
        examples=["srun"],
        title="Launcher",
    )


class ProjectAllocation(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(
        ...,
        description="Unique identifier of the project allocation.",
        examples=["alloc-001"],
        title="Id",
    )
    entries: list[AllocationEntry] = Field(
        ...,
        description="Allocation entries describing usage and limits.",
        title="Entries",
    )
    project_uri: str = Field(
        ..., description="URI of the associated project resource", title="Project Uri"
    )
    capability_uri: str = Field(
        ...,
        description="URI of the associated capability resource",
        title="Capability Uri",
    )


class Resource(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(
        ...,
        description="The unique identifier for the object. Typically a UUID or URN.",
        examples=["urn:iri:object:1234"],
        title="Id",
    )
    name: str | None = Field(
        None,
        description="The long name of the object.",
        examples=["Perlmutter GPU"],
        title="Name",
    )
    description: str | None = Field(
        None,
        description="Human-readable description of the object.",
        examples=["High-performance GPU compute resource"],
        title="Description",
    )
    last_modified: AwareDatetime = Field(
        ...,
        description="ISO 8601 timestamp when this object was last modified.",
        examples=["2026-02-21T12:00:00Z"],
        title="Last Modified",
    )
    group: str | None = Field(
        None,
        description="Logical grouping of the resource",
        examples=["frontend"],
        title="Group",
    )
    current_status: Status | None = Field(
        None,
        description="The current status comes from the status of the last event for this resource",
        examples=["up"],
    )
    resource_type: ResourceType = Field(
        ..., description="Type of the resource", examples=["service"]
    )
    supported_endpoints: list[Endpoint] | None = Field(
        None,
        description="a list of endpoints where this resource can be used",
        title="Supported Endpoints",
    )
    self_uri: str = Field(
        ..., description="The canonical URL of this object", title="Self Uri"
    )
    site_uri: str = Field(
        ...,
        description="URI of the site where this resource is located",
        title="Site Uri",
    )
    capability_uris: list[str] = Field(
        ...,
        description="The list of capabilities in this resource",
        title="Capability Uris",
    )


class Task(BaseModel):
    id: str = Field(
        ...,
        description="Unique identifier of the task",
        examples=["task-123"],
        title="Id",
    )
    status: TaskStatus | None = Field(
        "pending", description="Current status of the task", examples=["pending"]
    )
    result: dict[str, Any] | None = Field(
        None, description="Result of the task execution, if available", title="Result"
    )
    command: TaskCommand | None = Field(
        None, description="Command associated with this task"
    )


class UserAllocation(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(
        ...,
        description="Unique identifier of the user allocation.",
        examples=["user-alloc-42"],
        title="Id",
    )
    user_id: str = Field(
        ...,
        description="Identifier of the user receiving this allocation.",
        examples=["user-123"],
        title="User Id",
    )
    entries: list[AllocationEntry] = Field(
        ...,
        description="Allocation entries describing usage and limits.",
        title="Entries",
    )
    project_allocation_uri: str = Field(
        ...,
        description="URI of the associated project allocation",
        title="Project Allocation Uri",
    )


class Job(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(
        ...,
        description="Unique identifier of the job",
        examples=["job-12345"],
        title="Id",
    )
    status: JobStatus | None = Field(None, description="Current status of the job")
    job_spec: JobSpec | None = Field(
        None, description="Specification used to create the job"
    )
